#!/bin/bash

yum install -y python3-devel SDL{,_gfx,image,mixer,net,Pango,sound,ttf}-devel
yum install -y make automake gcc gcc-c++
yum install -y mercurial git ***devtools***

pip3 install virtualenv

mkdir -p /opt


cd /opt
git clone https://github.com/elliotnunn/bling


cd /opt/bling

wget -O chicago.bdf https://raw.githubusercontent.com/danfe/fonts/master/Chicago-12.bdf

virtualenv blingenv
source blingenv/bin/activate

pip3 install numpy


cd /opt
hg clone https://bitbucket.org/pygame/pygame


cd /opt/pygame

python3 setup.py build
python3 setup.py install
