#!/bin/bash

rm -rf /opt/bling /opt/pygame /opt/bcm2835* /lib/systemd/system/bling.service

yum install -y python3-devel SDL{,_gfx,_image,_mixer,_net,_Pango,_sound,_ttf}-devel
yum install -y gcc mercurial git python3-pip python3-numpy
yum install -y net-tools avahi

python3-pip install virtualenv

# Initial wifi network specified in args
nmcli dev wifi con "$1" password "$2"

# Disable graphical boot by default
systemctl set-default multi-user.target


# Install all the really dodgy stuff
mkdir -p /opt

cd /opt
	git clone https://github.com/elliotnunn/bling
	hg clone https://bitbucket.org/pygame/pygame
	wget -q -O - http://www.airspayce.com/mikem/bcm2835/bcm2835-1.38.tar.gz | tar -xzf -

cd /opt/bcm2835*
	./configure
	make
	make install

cd /opt/bling
	cp bling.service /lib/systemd/system/
	systemctl daemon-reload
	systemctl enable bling.service
	
	wget -O chicago.bdf https://raw.githubusercontent.com/danfe/fonts/master/Chicago-12.bdf
	
	virtualenv blingenv
	cp -R /lib/python3*/site-packages/numpy blingenv/lib/python3*/site-packages/

cd /opt/bling/hw/st7565
	make

cd /opt/pygame
	source /opt/bling/blingenv/bin/activate
	python3 setup.py build
	python3 setup.py install
